"""
Neural FOXP2 Configuration Module

Contains all hyperparameters and configuration settings for the pipeline.
"""
from dataclasses import dataclass, field
from typing import List, Tuple


@dataclass
class Config:
    # Model settings
    model_name: str = "meta-llama/Llama-3.1-8B-Instruct"
    hf_token: str = ""  # Set your HuggingFace token here
    
    # Layer range for SAE training
    layer_range: List[int] = field(default_factory=lambda: list(range(8, 24)))
    
    # SAE hyperparameters
    n_features: int = 1024
    epochs: int = 150
    lr: float = 5e-4
    lambda_sparse: float = 5e-3
    
    # Data settings
    target_language: str = "hindi"
    n_prompts: int = 2500
    seed: int = 42
    
    # Stage I settings
    top_k_features: int = 50
    lift_alphas: Tuple[float, ...] = (0.5, 1.0, 2.0, 5.0, 10.0, 15.0)
    
    # Stage II settings
    r_max: int = 12
    min_window: int = 3
    max_window: int = 6
    n_bootstrap: int = 20
    n_prompts_svd: int = 1000
    n_prompts_stability: int = 1200
    
    # Stage III setting
    lambda_grid: List[float] = field(default_factory=lambda: [0.5, 1.0, 2.0, 4.0])
    beta_ratios: List[float] = field(default_factory=lambda: [0.0, 0.5, 1.0])
    n_eval_prompts: int = 400
    n_prototype_prompts: int = 200
    
    # Weak prompts for testing
    weak_prompts: List[str] = field(default_factory=lambda: 
    [ 
        "Explain how rain forms.",
        "Explain why the sky appears blue.",
        "Explain the water cycle.",
        "Explain how plants grow.",
        "Explain how gravity works.",
        "Explain how photosynthesis works.",
        "Explain why seasons change.",
        "Explain how wind forms.",
        "Explain how clouds form.",
        "Explain why oceans have tides.",
        "Explain how lightning forms.",
        "Explain why volcanoes erupt.",
        "Explain how earthquakes happen.",
        "Explain why leaves change color.",
        "Explain how snow forms.",
        "Explain why deserts are dry.",
        "Explain how mountains form.",
        "Explain how rivers shape land.",
        "Explain why ice floats on water.",
        "Explain how rainbows form.",
        "Explain how the human heart works.",
        "Explain how the brain processes information.",
        "Explain how muscles move the body.",
        "Explain how digestion works.",
        "Explain how the immune system protects the body.",
        "Explain why people need sleep.",
        "Explain how memory works.",
        "Explain how the lungs exchange oxygen.",
        "Explain why exercise improves health.",
        "Explain how bones support the body.",
        "Explain how electricity flows in a circuit.",
        "Explain how batteries store energy.",
        "Explain how solar panels generate power.",
        "Explain how magnets attract objects.",
        "Explain how computers process information.",
        "Explain how the internet works.",
        "Explain how satellites orbit Earth.",
        "Explain how GPS determines location.",
        "Explain how airplanes stay in the air.",
        "Explain how rockets reach space.",
        "Why do animals migrate?",
        "Why do birds build nests?",
        "Why do plants need sunlight?",
        "Why do people learn languages?",
        "Why do people form habits?",
        "Why do humans cooperate?",
        "Why do some materials conduct electricity?",
        "Why do metals expand when heated?",
        "Why does ice melt?",
        "Why does water boil?",
        "Why does the moon change shape?",
        "Why does the Earth rotate?",
        "Why does the Earth orbit the Sun?",
        "Why do stars shine?",
        "Why do galaxies form?",
        "Why do some animals hibernate?",
        "Why do animals camouflage themselves?",
        "Why do humans dream?",
        "Why do people feel emotions?",
        "Why do people enjoy music?",
        "Describe how a seed grows into a plant.",
        "Describe how a butterfly develops.",
        "Describe how the human brain learns.",
        "Describe how rain nourishes ecosystems.",
        "Describe how rivers reach the ocean.",
        "Describe how mountains influence climate.",
        "Describe how forests support wildlife.",
        "Describe how ecosystems stay balanced.",
        "Describe how coral reefs form.",
        "Describe how animals adapt to environments.",
        "Describe the process of learning a new skill.",
        "Describe how people solve complex problems.",
        "Describe how teamwork improves results.",
        "Describe how practice builds expertise.",
        "Describe how habits develop over time.",
        "Describe how knowledge spreads through society.",
        "Describe how communities organize resources.",
        "Describe how technology shapes communication.",
        "Describe how transportation connects cities.",
        "Describe how information travels online.",
        "How do plants absorb nutrients?",
        "How do animals find food?",
        "How do birds navigate long distances?",
        "How do insects communicate?",
        "How do trees grow tall?",
        "How do fish breathe underwater?",
        "How do whales communicate?",
        "How do bees make honey?",
        "How do ants organize colonies?",
        "How do animals survive in cold climates?",
        "How does learning improve over time?",
        "How does practice affect memory?",
        "How does repetition strengthen understanding?",
        "How does curiosity encourage discovery?",
        "How does reflection improve thinking?",
        "How does reading expand knowledge?",
        "How does discussion improve ideas?",
        "How does feedback improve performance?",
        "How does planning support success?",
        "How does patience help problem solving?",
        "Explain the importance of clean water.",
        "Explain the importance of education.",
        "Explain the importance of communication.",
        "Explain the importance of cooperation.",
        "Explain the importance of critical thinking.",
        "Explain the importance of creativity.",
        "Explain the importance of perseverance.",
        "Explain the importance of curiosity.",
        "Explain the importance of discipline.",
        "Explain the importance of honesty.",
        "Describe the benefits of regular exercise.",
        "Describe the benefits of good nutrition.",
        "Describe the benefits of sleep.",
        "Describe the benefits of reading.",
        "Describe the benefits of teamwork.",
        "Describe the benefits of clear communication.",
        "Describe the benefits of planning.",
        "Describe the benefits of reflection.",
        "Describe the benefits of curiosity.",
        "Describe the benefits of persistence.",
        "Explain how cities develop over time.",
        "Explain how trade connects countries.",
        "Explain how markets function.",
        "Explain how businesses grow.",
        "Explain how innovation spreads.",
        "Explain how technology changes society.",
        "Explain how education systems evolve.",
        "Explain how transportation networks develop.",
        "Explain how communication technologies advance.",
        "Explain how energy systems operate.",
        "Why do people explore new places?",
        "Why do cultures develop traditions?",
        "Why do societies create laws?",
        "Why do economies grow?",
        "Why do people share stories?",
        "Why do communities celebrate festivals?",
        "Why do people cooperate in groups?",
        "Why do people seek knowledge?",
        "Why do people invent tools?",
        "Why do societies value education?",
        "Describe how languages change over time.",
        "Describe how cultures influence behavior.",
        "Describe how traditions form.",
        "Describe how knowledge is preserved.",
        "Describe how stories pass through generations.",
        "Describe how art expresses ideas.",
        "Describe how music influences emotions.",
        "Describe how literature shapes thinking.",
        "Describe how science advances understanding.",
        "Describe how research leads to discovery.",
        "How does communication shape relationships?",
        "How does cooperation improve outcomes?",
        "How does trust develop between people?",
        "How does leadership influence groups?",
        "How does collaboration improve innovation?",
        "How does culture shape communication?",
        "How does technology influence learning?",
        "How does travel broaden perspective?",
        "How does curiosity drive exploration?",
        "How does knowledge influence decision making?",
        "Explain how ecosystems respond to change.",
        "Explain how biodiversity supports stability.",
        "Explain how conservation protects nature.",
        "Explain how pollution affects environments.",
        "Explain how recycling reduces waste.",
        "Explain how renewable energy helps sustainability.",
        "Explain how forests regulate climate.",
        "Explain how oceans influence weather.",
        "Explain how wetlands support wildlife.",
        "Explain how soil supports plant life.",
        "Why do ecosystems depend on balance?",
        "Why do species evolve over time?",
        "Why do habitats support biodiversity?",
        "Why do plants grow toward sunlight?",
        "Why do animals form social groups?",
        "Why do ecosystems change slowly?",
        "Why do organisms compete for resources?",
        "Why do organisms adapt to environments?",
        "Why do species go extinct?",
        "Why do ecosystems recover after disturbances?",
        "Describe how learning develops from childhood.",
        "Describe how curiosity begins early in life.",
        "Describe how observation leads to discovery.",
        "Describe how experimentation builds knowledge.",
        "Describe how questions lead to insight.",
        "Describe how science explains natural phenomena.",
        "Describe how reasoning supports understanding.",
        "Describe how ideas evolve over time.",
        "Describe how knowledge accumulates.",
        "Describe how discovery changes society.",
        "How does reasoning support good decisions?",
        "How does analysis improve understanding?",
        "How does observation support science?",
        "How does measurement improve accuracy?",
        "How does experimentation reveal patterns?",
        "How does comparison reveal differences?",
        "How does classification organize knowledge?",
        "How does modeling help explain systems?",
        "How does prediction guide planning?",
        "How does evidence support conclusions?",
        "Explain how time management improves productivity.",
        "Explain how goal setting guides progress.",
        "Explain how focus improves performance.",
        "Explain how persistence supports success.",
        "Explain how reflection improves learning.",
        "Explain how feedback helps improvement.",
        "Explain how collaboration strengthens outcomes.",
        "Explain how organization supports efficiency.",
        "Explain how discipline builds habits.",
        "Explain how motivation drives effort.",
        "Why do people set goals?",
        "Why do people reflect on experiences?",
        "Why do people seek improvement?",
        "Why do people develop routines?",
        "Why do people adapt to change?",
        "Why do people share knowledge?",
        "Why do people mentor others?",
        "Why do people pursue challenges?",
        "Why do people solve problems creatively?",
        "Why do people learn from mistakes?",
        "Describe how transportation shapes cities.",
        "Describe how roads connect regions.",
        "Describe how railways move goods.",
        "Describe how shipping supports trade.",
        "Describe how airports enable travel.",
        "Describe how logistics systems operate.",
        "Describe how supply chains function.",
        "Describe how infrastructure supports development.",
        "Describe how energy powers cities.",
        "Describe how communication connects communities.",
        "How does transportation influence trade?",
        "How does infrastructure support growth?",
        "How does technology improve efficiency?",
        "How does innovation transform industries?",
        "How does research influence technology?",
        "How does automation affect productivity?",
        "How does data improve decision making?",
        "How does communication speed collaboration?",
        "How does design influence usability?",
        "How does engineering solve practical problems?",
        "Explain how ideas spread through communities.",
        "Explain how social networks share information.",
        "Explain how education builds knowledge.",
        "Explain how communication improves understanding.",
        "Explain how debate refines ideas.",
        "Explain how collaboration creates innovation.",
        "Explain how leadership guides teams.",
        "Explain how shared goals motivate groups.",
        "Explain how trust supports cooperation.",
        "Explain how knowledge shapes progress.",
        "Why do communities share resources?",
        "Why do societies invest in education?",
        "Why do people build institutions?",
        "Why do communities support cooperation?",
        "Why do societies value innovation?",
        "Why do organizations pursue efficiency?",
        "Why do people create systems of governance?",
        "Why do groups develop rules?",
        "Why do societies preserve history?",
        "Why do cultures encourage creativity?",
        "Describe how exploration expands knowledge.",
        "Describe how travel reveals new perspectives.",
        "Describe how discovery inspires curiosity.",
        "Describe how innovation changes industries.",
        "Describe how science improves technology.",
        "Describe how research advances medicine.",
        "Describe how engineering solves problems.",
        "Describe how design improves everyday life.",
        "Describe how learning transforms understanding.",
        "Describe how collaboration builds knowledge.",
        "How does curiosity encourage learning?",
        "How does exploration reveal patterns?",
        "How does experimentation produce insight?",
        "How does study deepen knowledge?",
        "How does reflection strengthen understanding?",
        "How does teaching reinforce learning?",
        "How does discussion clarify ideas?",
        "How does collaboration expand creativity?",
        "How does diversity enrich thinking?",
        "How does inquiry lead to discovery?",
        "Explain how complex systems remain stable.",
        "Explain how feedback loops influence systems.",
        "Explain how networks connect components.",
        "Explain how patterns emerge in nature.",
        "Explain how order develops in systems.",
        "Explain how interactions create structure.",
        "Explain how processes repeat over time.",
        "Explain how cycles shape natural systems.",
        "Explain how balance supports stability.",
        "Explain how change drives adaptation."
    ])


# Global config instance
config = Config()


